language: node_js
node_js:
- stable
- '12'
install:
- npm i
script:
- npm test
deploy:
  provider: npm
  email: gautaz@users.noreply.github.com
  api_key:
    secure: Q6LHccrtumh6vwJNR7ed4xGEgO218b6JybdAjgKE/IkaAw971bmsqHhEbrxRCbRRwFg3ARjsp6gsuPguTcVTYy91CFbEC73VguNBC4KOqcS4D+7EmWiZqeW1MH+47zCYMKBMBoiuaEGNVQ6zbRm3PjA10aDsKOUgexSpwNl+EkpQ5mVwgxlA+YfwMdtNCMUddW/XjkcKrQAexVN88X/F6uB1JNhP9OdhDdWAmuFam4DLENKm2tOgslBk1RCLumcQmfYuna/1hcfie6f/ynLTHMQ36uIra29KoBCYAYFNmRfcERC21Fyd4MaLirVLfUS+SbMQX/OBvS9Z5RnKa2ZMwhTpqQLyx+SBQ+6sQYfbD8jwayHxrm+jnnwKeHQTfzpFkyqB2PaRrX2dZKAd8vPr81XZFqNIRyyIbIes/7AykC18goGfLDvL5V6SA0IcPr0VPJo7SZ/vXtenDdLaENNrfZlU42umosx7wkKMUe4bCkROl6y6EiIBpYAfX/87DTwqACNVS0VqEW2/iNyj6opIZoCo3SLxeDGEt/a3SQFSAl6KXIfzyYrDWE29ObeRD38GWoK1r9XK6rPc3/qXkK86ldRK6z4m+PXYx6TbIZhY56bCjO2G8vVUdFv3hLqaB7KIcW8SQCBClJ75/R4k9JEBJ515NJG8eoUM8TgE99G3dso=
  on:
    tags: true
    repo: r2d2bzh/yac
    branch: main
  skip_cleanup: 'true'
